### ISSUE TITLE
RFC URL endpoint building

### ISSUE THREAD

**Issue by hachreak** [inveniosoftware/invenio-records-rest#101]
There is a specific reason why to construct the url endpoint is used the `key` of `RECORDS_REST_ENDPOINTS` and sometimes the `pid_type`?
See:
 - construction [with key](https://github.com/inveniosoftware/invenio-records-rest/blob/master/invenio_records_rest/views.py#L227) and [here](https://github.com/inveniosoftware/invenio-records-rest/blob/master/invenio_records_rest/views.py#L247), [here](https://github.com/inveniosoftware/invenio-records-rest/blob/master/invenio_records_rest/views.py#L265) and [here](https://github.com/inveniosoftware/invenio-records-rest/blob/master/invenio_records_rest/views.py#L277) `RecordsListOptionsResource.view_name.format(endpoint),`
 - construction [with pid_type](https://github.com/inveniosoftware/invenio-records-rest/blob/master/invenio_records_rest/views.py#L450)
 - construction [with pid_type](https://github.com/inveniosoftware/invenio-records-rest/blob/master/invenio_records_rest/views.py#L513) from the record. `endpoint = '.{0}_item'.format(pid.pid_type)`

Can we simplify and use only one way?
Maybe the best solution is to use the `pid_type` everywhere. WDYT? There are some contraindications?

-----------------------------------------------------------
ping @jirikuncar @lnielsen @tiborsimko

**Comment by jirikuncar** [comment]
There *must* exist one key per `pid_type` (see https://github.com/inveniosoftware/invenio-records-rest/blob/master/invenio_records_rest/utils.py#L104-L126). However, one can have multiple endpoints for same `pid_type`. We will have to address it in #99 and #100.

**Comment by kaplun** [comment]
Hi! What is the status of this issue? In INSPIRE we are trying to move to official `invenio-pidstore`, (see https://github.com/inveniosoftware/invenio-pidstore/pull/63#issuecomment-248244449) but this is currently blocked by this specific usage of `pid_type` in building the endpoints.
