### ISSUE TITLE
RFC merge RECORDS_REST_SORT_OPTIONS inside RECORDS_REST_ENDPOINTS

### ISSUE THREAD

**Issue by hachreak** [inveniosoftware/invenio-records-rest#104]
**Problem**

Currently we have a special configuration called `RECORDS_REST_SORT_OPTIONS` that specifies the sort configuration for each `index`.

 1. It can be error prone because the user have to specify the index name inside `RECORDS_REST_ENDPOINTS` and, in the same time, inside `RECORDS_REST_SORT_OPTIONS`.

 2. In addition, It is not intuitive because the convention for the dictionary key is different from `RECORDS_REST_ENDPOINTS` (where as `key` is used the `pid_type`).

 3. Inside [sorter.py](https://github.com/inveniosoftware/invenio-records-rest/blob/master/invenio_records_rest/sorter.py#L140-L148) we set the sort options to the `search_class`. So, why we don't do it directly?

**Proposal**
Can we directly specify the default sort configuration inside the [search class](https://github.com/inveniosoftware/invenio-records-rest/blob/master/invenio_records_rest/config.py#L44) and remove `RECORDS_REST_SORT_OPTIONS`?

----------------------------------------------------
cc @inveniosoftware/triagers 
see https://github.com/inveniosoftware/invenio-records-rest/issues/99

**Comment by lnielsen** [comment]
``RECORDS_REST_SORT_OPTIONS`` is also used by UI: https://github.com/zenodo/zenodo/blob/master/zenodo/config.py#L508

I think this needs to be treated as part of how Records-REST should be configured - see #64 

The reason to keep it separate is because the sorting is fully independent of the search. You can rip it out and replace it with something else.

**Comment by hachreak** [comment]
could you share the configuration inside the `seach_class` as you say in #64 proposal 1?
It looks like the natural point where share the configuration for facets, sort, index, doc_type and max_result_window.

**Comment by jirikuncar** [comment]
I'm also for keeping it separate as it's not part of the main search API.
