### ISSUE TITLE
Make the use of marhsmallow optionnal in serializers

### ISSUE THREAD

**Issue by jma** [inveniosoftware/invenio-records-rest#110]
Sometimes using `marhsmallow` in serializers can be overkill. We can make the schema optional in `invenio_record_rest.serializers.json:JSONSerializer`. Similar to [https://github.com/inveniosoftware/invenio-marc21/blob/master/invenio_marc21/serializers/marcxml.py#L54](url).

**Comment by lnielsen** [comment]
Also, we should add support for context and refactor the classes a bit to allow for better use as mixing
