### ISSUE TITLE
sorter: missing option

### ISSUE THREAD

**Issue by PXke** [inveniosoftware/invenio-records-rest#112]
Dear all, 

Currently the default sorter factory is filtering the options given by configuration to keep only the ordering. 

https://github.com/inveniosoftware/invenio-records-rest/blob/19fdd5b38d00f37d8968f5d887b0fcfb6d233254/invenio_records_rest/sorter.py#L149

In some case it is possible to ask for sorting on a field that is sometimes missing from some record thanks to the "missing" parameter: 

https://www.elastic.co/guide/en/elasticsearch/reference/current/search-request-sort.html#_missing_values

It is at my knowledge not possible to do so in Invenio. 

What I would like to do if it is approved. Is to alter the code of `sorter.py` to keep the missing option. 

To do so I see several solution, we can turn fields in a dictionary and put the options that should reach elastic search in this dict. 

```
RECORDS_REST_SORT_OPTIONS` = dict(
    records=dict(
        bestmatch=dict(
            title=_('Relevance'),
            fields=dict(name='control_number', missing='_last'),
            default_order='desc',
            order=1,
        ),
    ),
)
```

We can also prefix the options name in the RECORDS_REST_SORT_OPTIONS dict. 

```
RECORDS_REST_SORT_OPTIONS` = dict(
    records=dict(
        bestmatch=dict(
            title=_('Relevance'),
            fields=['control_number'],
            default_order='desc',
            order=1,
            ES_missing='_last',
        ),
    ),
)
```

I am open to all suggestions and really happy to get feedbacks.

Bests,

**Comment by PXke** [comment]
Affecting @lnielsen  as he has the most written line on this module.

**Comment by jirikuncar** [comment]
@PXke have you tried:

```python
RECORDS_REST_SORT_OPTIONS` = dict(
    records=dict(
        bestmatch=dict(
            title=_('Relevance'),
            fields=[dict(name='control_number', missing='_last')],  # use list of dicts
            default_order='desc',
            order=1,
        ),
    ),
)
```

--
PS: Use `{}` instead of `dict()` to minimize number of function calls.

**Comment by audub** [comment]
We ended up doing: 

```
RECORDS_REST_SORT_OPTIONS = {
    'records': {
        'mostrecent': {
            'title': 'Relevance',
            'fields': [{
                'control_number': {
                    'missing': '_last',
                    'ignore_unmapped': True
                }
            }],
            'default_order': 'desc',
            'order': 2,
        },
    },
}
```

It seems to work :)
