### ISSUE TITLE
Serializing large number of results

### ISSUE THREAD

**Issue by kaplun** [inveniosoftware/invenio-records-rest#113]
In order to implement inspirehep/inspire-next#1304, we need to serialize in CSV format _all_ the citations that a given arbitrarily large set of records have received. (In particular see: https://github.com/inspirehep/inspire-next/issues/1304#issuecomment-231310195)

That means that for every record involved we'd have to query ES for referring records and then iterating over all these, we should produce the CSV output.

I can very well see how to do it for a single record, however is there a way to serialize with this criteria _all_ records matching a given query? (and not e.g. the first 10 in the search window).

**Comment by jirikuncar** [comment]
@kaplun you can rely on a cache in JSON Resolver to speed up `$ref` resolution, however there is no immediate plan on re-implementing *BibFormat* cache from Invenio 1.x.

Alternatively, you can provide custom search class that can do some black magic and optimization so the serializer doesn't have to fetch any extra data.

**Comment by kaplun** [comment]
@jirikuncar in this case I am not expanding with references: the record in a given set are those *referred*. So say my search result has 100 records. These are going to be cited by e.g. 2000 more records. The serializer should then build the CSV by reading properties from the 2000 records and the 100 initial one in order to have one row per citation.

My main issue is that the `serialize_search` API is fed automatically with the paginated results of a given query, thus it would only receive e.g. the first 10 records of the above 100. Somehow a trick could be that I ignore the search_result and I access directly the search query in order to replay it via `scan` to obtain the whole 100 records. However I think in `serialize_search` I don't have access to the original query, have I?

**Comment by jirikuncar** [comment]
> I think in `serialize_search` I don't have access to the original query

that's why I was proposing that

> you can provide custom search class

**Comment by jirikuncar** [comment]
@kaplun check `search_class` key in https://github.com/inveniosoftware/invenio-records-rest/blob/master/invenio_records_rest/config.py#L44 (http://pythonhosted.org/invenio-records-rest/api.html#invenio_records_rest.config.RECORDS_REST_ENDPOINTS).

**Comment by kaplun** [comment]
@jirikuncar thanks for the pointers. I have to admit I am lost in the several levels of abstraction.

I understand I can specify a custom `search_class` that inherit from `RecordsSearch` (indeed we are doing it in INSPIRE in https://github.com/inspirehep/inspire-next/blob/master/inspirehep/modules/search/api.py#L80). However, by looking at its signature it's not clear to me how it is going to be used. Is it `faceted_search` the method I should extend in order to capture the query? I see `faceted_search` returns an instance of the class `RecordsFacetedSearch` which inherits from `FacetedSearch`, which has a method `search`. Is this last one actually the responsible for providing the hits to `serialize_search`?

**Comment by lnielsen** [comment]
@kaplun Can I close this issue? and did you find a solution for INSPIRE? I can't see what we can do from the Records-REST point of view right now (except better documentation, which is already reported).

**Comment by kaplun** [comment]
I haven't seen the question back then, sorry @lnielsen. Nope we have not yet attacked the problem.
