### ISSUE TITLE
views: get the search_index from the config variable

### ISSUE THREAD

**Issue by zazasa** [inveniosoftware/invenio-records-rest#131]
The `search_index` option set in the `RECORDS_REST_ENDPOINTS` is not respected by the search api.
Indeed the search_index seems to be always equal to "_all" .
I verified that hardcoding the index here https://github.com/inveniosoftware/invenio-records-rest/blob/master/invenio_records_rest/views.py#L436 :
```python
search = self.search_class(index='test-index').params(version=True)
```
seems working, but i had some problem reading this parameter from the config.

**Comment by jirikuncar** [comment]
@zazasa @audub are you planning to submit a PR?

**Comment by zazasa** [comment]
I am not sry, it is not clear enough for me to fix it. Maybe we can talk about it in these days so I can do it.

**Comment by dinosk** [comment]
@zazasa I could not reproduce this, I noted though that the search index registered will be the one that is there at the [initialization](https://github.com/inveniosoftware/invenio-records-rest/blob/master/invenio_records_rest/ext.py#L107) of the module. Changing it afterwards won't work.
