### ISSUE TITLE
views: PIDConverter prevents from sending additional data during a GET of a deleted record

### ISSUE THREAD

**Issue by nharraud** [inveniosoftware/invenio-records-rest#152]
**Problem:**
In B2SHARE we would like to return the reason why a record was deleted when a client makes a GET request on a deleted request.
This is currently not possible as the [`PIDConverter`](https://github.com/inveniosoftware/invenio-records-rest/blob/d36b628c5687ca7342ce756bf42da53befb18eb7/invenio_records_rest/utils.py#L189) will [raise a `PIDDeletedRESTError` exception](https://github.com/inveniosoftware/invenio-records-rest/blob/d36b628c5687ca7342ce756bf42da53befb18eb7/invenio_records_rest/utils.py#L156) which bypasses the serializer.

I don't have yet any clear solution for this problem.
This is not an urgent issue.

**Comment by hachreak** [comment]
Do you think about use a different `PIDConverter` overwriting it in [RECORDS_REST_ENDPOINTS]( https://github.com/inveniosoftware/invenio-records-rest/blob/master/invenio_records_rest/config.py#L56) configuration?
Something like `item_route='/records/<mypidconverter(recid):pid_value>',`

**Comment by nharraud** [comment]
That would be the most backward compatible solution yes. But do we deprecate the previous one? The current behavior is quite limiting.

**Comment by lnielsen** [comment]
Records-UI already have a solution so it should be aligned with that.

**Comment by lnielsen** [comment]
https://github.com/inveniosoftware/invenio-records-ui/blob/master/invenio_records_ui/views.py#L67-L73

**Comment by slint** [comment]
@lnielsen @nharraud Apart from implementing a similar method as the one in `invenio-records-ui`, part of the flexibility that the particular error handler has, is the fact that the raised exception is an subclass of [`invenio_pidstore.errors.ResolverError`](https://github.com/inveniosoftware/invenio-pidstore/blob/c2165b6ecfc56b7d128b27f09f2d7e9396402d85/invenio_pidstore/errors.py#L52) (or its subclasses), which also contains some extra information (eg. the deleted record in case of a [`PIDDeletedError`](https://github.com/inveniosoftware/invenio-pidstore/blob/c2165b6ecfc56b7d128b27f09f2d7e9396402d85/invenio_pidstore/errors.py#L66)).

As part of adding the extra handlers, maybe it would be good to include the original PIDStore exception in the [re-raised exception](https://github.com/inveniosoftware/invenio-records-rest/blob/c6993d9355bc35ff2522d9eea5c63e74407075f5/invenio_records_rest/utils.py#L149-L161):

```python
try:
    return resolver.resolve(pid_value)
except PIDDeletedError as exc:
    raise PIDDeletedRESTError(original_error=exc)

# ...or...

except PIDDeletedError as exc:
    from future.utils import raise_from
    raise_from(PIDDeletedRESTError(), exc)
    # Equivalent to Python 3:
    # raise PIDDeletedRESTError() from exc

# ...then in the handler:
@blueprint.errorhandler(PIDDeletedRESTError)
def err_handler(error):
    return jsonify({
        'status': error.code,
        'message': error.descriptionm
        'removal_reason': error.original_error.record.get('removal_reason'),
        # or if `from_raise` was used:
        # 'removal_reason': error.__cause__.record.get('removal_reason'),
    })
```

**Comment by lnielsen** [comment]
@slint Yes, actually the current way of catching and rasing a new exception is likely not very good, so as minimum we should reraise with same stacktrace and the included data.

**Comment by lnielsen** [comment]
Now the problem is that we likely need a serliazer or simiarl to customize what is returned in the tombstone.

**Comment by slint** [comment]
I was thinking of a `[ExceptionClass -> "path.to.handler.function"]` dictionary in config, which will be registered using `blueprint.register_error_handler` as part of the [`create_blueprint`](https://github.com/inveniosoftware/invenio-records-rest/blob/c6993d9355bc35ff2522d9eea5c63e74407075f5/invenio_records_rest/views.py#L67-L91) function... The handler function could be something more elaborate that uses a schema to serialize the response

**Comment by nharraud** [comment]
Could we have the handler in the RECORDS_REST_ENDPOINTS config rather than a separate config variable? That way we could have a separate handler per endpoint. There can also be a default handler in a separate config variable.

Can we suppose that there will be only one format returned in case of error. Example: request "accept-type:application/marcxml" -> error -> return JSON
I think that it can make sense otherwise you would have conflict between 406 (not-acceptable) and 404/409/...
