### ISSUE TITLE
docs: extending API Docs

### ISSUE THREAD

**Issue by diegodelemos** [inveniosoftware/invenio-records-rest#163]
- [x] Add **permissions** documentation.
- [x] Add **query factory/sorting/facets** documentation.
- [x] Add **decorators** documentation (for @pass_record -> LazyPIDValue).
- [x] Add **utils** documentation (for LazyPIDValue, PIDConverter).
- [x] Add **links** documentation.

**Comment by diegodelemos** [comment]
@lnielsen should we split each element in the list into different issues?

**Comment by krzysztof** [comment]
WIP PR https://github.com/inveniosoftware/invenio-records-rest/pull/167

**Comment by krzysztof** [comment]
serializers moved to separate Issue: https://github.com/inveniosoftware/invenio-records-rest/issues/169
