### ISSUE TITLE
es5 support: review queries

### ISSUE THREAD

**Issue by lnielsen** [inveniosoftware/invenio-records-rest#173]
In order to support ES5+6, review if there are major changes in the query DSL so that queries we sent to ES needs to customized for both ES2, 5 and 6.

- Filters
- Aggregations
- Sorting

**Comment by krzysztof** [comment]
https://www.elastic.co/guide/en/elasticsearch/reference/5.6/breaking_50_search_changes.html

**Comment by krzysztof** [comment]
Some more information: https://github.com/orgs/inveniosoftware/teams/sprint/discussions/3
