### ISSUE TITLE
Multiple indices in Invenio_records_rest

### ISSUE THREAD

**Issue by PSvishnu93** [inveniosoftware/invenio-records-rest#220]
Is it possible to use multiple indices in a single app using invenio_records_rest? If possible which variables needs to be updated.

**Comment by lnielsen** [comment]
Yes, it's possible. See http://invenio-records-rest.readthedocs.io/en/latest/usage.html#configuration for details.

E.g. you can have ``/api/records/`` and ``/api/authors``. The ``/api/records/`` will search over an Elasticsearch alias named ``records``  which can search multiple indexes (e.g. ``records-record-v1.0.0`` and ``records-record-v1.1.0``. Similar goes for ``/api/authors``.
