### ISSUE TITLE
How to connect to elasticsearch running on a server other than localhost.

### ISSUE THREAD

**Issue by PSvishnu93** [inveniosoftware/invenio-records-rest#222]
I am trying to connect to elasticsearch running in a server other than localhost for eg: 10.9.9.12:9200. Which fields needs to be updated to access the elasticsearch.

**Comment by slint** [comment]
Elasticsearch connections are configured via the `invenio-search` package. You can have a look at the module's config docs: https://invenio-search.readthedocs.io/en/latest/configuration.html
