### ISSUE TITLE
fields: PersistentIdentifier not (de)serializing as expected

### ISSUE THREAD

**Issue by slint** [inveniosoftware/invenio-records-rest#232]
The [`.schemas.fields.PersistentIdentifier`](https://github.com/inveniosoftware/invenio-records-rest/blob/ada7d4d556d7b92cab88039bbfa87e4781e320ab/invenio_records_rest/schemas/fields/persistentidentifier.py#L20-L26) marshmallow field, is assuming a wrong method signature when overriding [`Field._deserialize`](https://marshmallow.readthedocs.io/en/2.x-line/api_reference.html#marshmallow.fields.Field._deserialize) and `Field._serialize`: 

```python
# wrong
...
def _deserialize(self, value, attr, context):
    # "context" is actually the original "data" passed to "Schema(...).load"
    # and not the "Schema(context=context).load(...)" (see docs link above)
    pid = context.get('pid')
    return pid.get('pid_value') if pid else missing
...

# correct
def _deserialize(self, value, attr, data):
    pid = self.context.get('pid')
    return pid.get('pid_value') if pid else missing
```

When addressing this, keep in mind that:

- When doing a `POST /api/records`, there will be no [`request.view_args['pid_value']`](https://github.com/inveniosoftware/invenio-records-rest/blob/ada7d4d556d7b92cab88039bbfa87e4781e320ab/invenio_records_rest/loaders/marshmallow.py#L87-L90) and thus it won't be available in the loader schema's context, since the route doesn't have the PID yet, opposed to e.g. `PUT /api/records/<pid(recid):pid_value>`. The PID [will be minted](https://github.com/inveniosoftware/invenio-records-rest/blob/ada7d4d556d7b92cab88039bbfa87e4781e320ab/invenio_records_rest/views.py#L596) though and [passed to the serializer](https://github.com/inveniosoftware/invenio-records-rest/blob/ada7d4d556d7b92cab88039bbfa87e4781e320ab/invenio_records_rest/views.py#L606-L607) and thus will be available in the context of `Field._serialize` [because of this guy](https://github.com/inveniosoftware/invenio-records-rest/blob/ada7d4d556d7b92cab88039bbfa87e4781e320ab/invenio_records_rest/serializers/marshmallow.py#L32-L33).
- When serializing **search results** (e.g. from a `GET /api/records/` endpoint) the `context['pid']` is not a [`invenio_pidstore.models.PersistentIdentifier`](https://github.com/inveniosoftware/invenio-pidstore/blob/bc2018ece0982955f639a48f54a7ff8ddedfe5d4/invenio_pidstore/models.py#L85), but actually a [`invenio_pidstore.fetchers.FetchedPID`](https://github.com/inveniosoftware/invenio-pidstore/blob/bc2018ece0982955f639a48f54a7ff8ddedfe5d4/invenio_pidstore/fetchers.py#L36-L52). It has `pid.pid_value` and `pid.pid_type`, but none of methods/attributes that the SQLAlchemy model does.
- Marshmallow has a pretty weird behaviour when it comes to loading/dumping fields that were not there originally. See [a bunch](https://github.com/marshmallow-code/marshmallow/issues/394) [of completely](https://github.com/marshmallow-code/marshmallow/issues/409) [confused people](https://github.com/marshmallow-code/marshmallow/issues/775) trying to understand what went so terribly wrong in their lives... The closest thing to a solution is either using `@post_load` or [this guy's custom `Generated` field](https://github.com/marshmallow-code/marshmallow/issues/394#issuecomment-183665368). This is not optimal of course because in either way it requires educating developers on how to use marshmallow properly. The gist of it is:
    - `default=<value or callable>` is for providing a value when **serializing**
    - `missing=<value or callable>` is for providing a value when **deserializing**
    - Neither `default` or `missing` have access to `context` or `data` in any way...
    - Two solutions:
        - Modify our `PersistentIdentifier` field to some sort of `Generator` magic (seems a bit cleaner for the end-user)
        - Define some sort of `@post_load` mixin

**Comment by ppanero** [comment]
@slint The changes are missing the tests:
- Test the new ``RecordMetadataSchemaJSONV1`` in order to check proper ``RECID_FIELD`` value injection.
- Cross check the ``test_marshmallow_load`` in ``test_marshmallow_loader.py``. Since the serializer is not declared the following assertion will never be correct:
```python
        assert 'pid' in data_dump.data.get('metadata')
```
- Create a test to check the serialization with the ``PersistentIdentifier`` field. 

Lastly and for consistency the name of ````test_marshmallow_loader.py`` should be changed to ``test_loader_marshmallow.py``.

**Comment by ppanero** [comment]
Fix in https://github.com/inveniosoftware/invenio-records-rest/pull/234
