### ISSUE TITLE
Logging of request to elasticsearch and the response

### ISSUE THREAD

**Issue by PSvishnu93** [inveniosoftware/invenio-records-rest#236]
Is there any way to log the request to elasticsearch and the response or the request to invenio_records_rest and its response from a flask API

**Comment by lnielsen** [comment]
Today there is not, but you can probably hack it in.

The search object is generated by a user-configurable factory (see https://github.com/inveniosoftware/invenio-records-rest/blob/master/invenio_records_rest/views.py#L529-L533). This means you subclass the execute method and implement the logging there.
