### ISSUE TITLE
config record_class has no effect

### ISSUE THREAD

**Issue by jma** [inveniosoftware/invenio-records-rest#238]
Given the config example: https://github.com/inveniosoftware/invenio-records-rest/blob/21486d5dc7b7ab3ea2204b5b7d6fbed540e8e0af/invenio_records_rest/config.py#L101
it is possible to specify a `record_class` entry, but it has no effect.

It seems that this should be specified as a werkzeug parameter such as:

```python
        item_route='/documents/<pid(rec, record_class=mymodule.MyRecordClass):pid_value>'
```

Thanks.

**Comment by lnielsen** [comment]
@equadon I remember you looked into this, but I don't remember what the conclusion was.

**Comment by equadon** [comment]
@lnielsen I must have missed referencing the issue in PR https://github.com/inveniosoftware/invenio-records-rest/pull/244. The conclusion was:
- The PID converter already supports `record_class`
- `record_class` in `RECORDS_REST_ENDPOINTS` is only used when creating records and the documentation was updated to reflect that
