### ISSUE TITLE
Facets and sorting are not working when prefix index is set

### ISSUE THREAD

**Issue by zzacharo** [inveniosoftware/invenio-records-rest#254]
Currently [`default_facet_factory`](https://github.com/inveniosoftware/invenio-records-rest/blob/ada7d4d556d7b92cab88039bbfa87e4781e320ab/invenio_records_rest/facets.py#L133) is searching for the unprefixed index name in your `RECORDS_REST_FACETS` config but when you search the prefixed one is passing [here](https://github.com/inveniosoftware/invenio-records-rest/blob/ada7d4d556d7b92cab88039bbfa87e4781e320ab/invenio_records_rest/query.py#L48). The same should be taken in consideration for the `sorter_factory`

**Comment by slint** [comment]
Addressed by #256. Needs https://github.com/inveniosoftware/invenio-search/commit/0a6055c1a17ce082c2ef57f00208a0c067b630eb to be released.

**Comment by slint** [comment]
Closed via #256, pending release of `invenio-records-rest`
