### ISSUE TITLE
views: protect against elasticsearch max records limit

### ISSUE THREAD

**Issue by lnielsen** [inveniosoftware/invenio-records-rest#28]
By default elasticsearch will only return 10k results. REST API should take this into account.

**Comment by nharraud** [comment]
I would differentiate two use cases:
- get records for the UI. This should be limited as the performances decrease with the number of pages.
- scroll all records for a specific processing. Elasticsearch allows scrolling the whole result set of a query.

The second use case requires the client to keep a "scrolling" token and give it back when it asks for the next batch of result.

There should be a specific permission for scrolling. We don't want somebody slowing down the server by just asking for the last page.

**Comment by lnielsen** [comment]
Yes, I agree. Here I was only thinking about the first use case, as currently it will throw an exception if you bypass the limit. I've opened issue #29 for the second use case.
