### ISSUE TITLE
support for composite aggregation

### ISSUE THREAD

**Issue by jacgeo111** [inveniosoftware/invenio-records-rest#283]
Elasticsearch supports the below composite aggregation. But when add the below aggregation in invenio, it does not working.
```
GET index/_search
{
    "aggs" : {
        "my_buckets": {
            "composite" : {
                "sources" : [
                    { "field_1": { "terms" : { "field": "field_1.keyword" } } },
                    { "field_2": { "terms" : { "field": "field_2".keyword } } }
                ]
            }
        }
     }
}
```
The invenio configuration was specified below.
```
app.config['RECORDS_REST_FACETS'] = {
    index_name: {
        "aggs" : {
            "my_buckets": {
                "composite" : {
                    "sources" : [
                        { "field_1": { "terms" : { "field": "field_1.keyword" } } },
                        { "field_2": { "terms" : { "field": "field_2".keyword } } }
                    ]
                }
            }
        }
    }
}
```

Is Invenio supports all the Elasticsearch aggregation methods?

**Comment by lnielsen** [comment]
What is the value of ``index_name`` and does it match the records rest index name?

Aggregations are passed [directly to ES](https://github.com/inveniosoftware/invenio-records-rest/blob/master/invenio_records_rest/facets.py#L121) without any modifications.

To debug the query going to Elasticsearch, you can put a breakpoint [here](https://github.com/inveniosoftware/invenio-records-rest/blob/master/invenio_records_rest/query.py#L54). The ``search`` variable is an Elasticsearch DSL object, and to see the ES query simply do:

```
print(search.to_dict())
```

See [details](https://elasticsearch-dsl.readthedocs.io/en/latest/search_dsl.html#the-search-object)

**Comment by rerowep** [comment]
I have a simular problem and I got following error from `elasticsearch_dsl/aggs.py`
```ValueError: A() can only accept dict with an aggregation ({"terms": {...}}). Instead it got ...```
I think also if you like to see the query you have to change following file: https://github.com/inveniosoftware/invenio-records-rest/blob/master/invenio_records_rest/facets.py#L167 as mentioned above.
