### ISSUE TITLE
views: html link in json serialization

### ISSUE THREAD

**Issue by hachreak** [inveniosoftware/invenio-records-rest#46]
**Problem**:
We show search results with a angular application (this is the [template used](https://github.com/inveniosoftware/invenio-search-ui/blob/master/invenio_search_ui%2Fstatic%2Ftemplates%2Finvenio_search_ui%2Fmarc21%2Fdefault.html#L3)): it receives the query results from `invenio-records-rest` json serializer that it's a list of records from elasticsearch, "improved" with some extra fields inserted by the serializer.
Currently, inside the json we have a field [links](https://github.com/inveniosoftware/invenio-records-rest/blob/master/invenio_records_rest%2Flinks.py#L33) that contains the url that point to the json version of the record (something like `/api/records/[:recid]`).
But, what we need is to have also a field `html_url` that contains the link to the "html version" of the record.

To be able to change the template as:

``` javascript
<h4>
  <a target="_self"
     ng-href="{{ record.links.html_url }}">
    {{ record.metadata.title_statement.title }}
   </a>
</h4>
```

---

cc @lnielsen @drjova @tiborsimko @jirikuncar @krzysztof

**Comment by nharraud** [comment]
The main problem is that the UI and the API are served by two different Flask application. Thus there is currently no easy way for the REST API to know the URL of the HTML view.

We could merge the two applications but it would conflict with the idea we had for versioning the API later, i.e: one application for each API version. That way the endpoints can't conflict.

**Comment by drjova** [comment]
Maybe is a dumb question, but could we just enrich the metadata with custom app-specific ``serializer``, is it any factory for that?

**Comment by hachreak** [comment]
A possible solution I think can be to use AngularJS route to show the search but also to see the record.
We will also improve the performances because the browser need only to load a html static template instead of a jinja one.

**Comment by lnielsen** [comment]
@drjova Yes, you can just do it in a custom serialiser. I think the main point here is that most people will need it, so would be nice with a reusable solution.

You can't use ``url_for`` to generate the URL for the records-ui for very good reasons. It think the best is simply to inject into records rest the right pattern for generating html links. Something along the lines of: 

```python
RECORDS_REST_ENDPOINTS = dict(
    records=dict(
        links_factory=default_link_factory('/records/{pid.pid_vaule}'),
    )
)
```

**Comment by drjova** [comment]
@hachreak IMHO it will be too complicated because you'll have one route handled differently depending on your location and duplicated templates etc, it would be nice if we just use angular for all routes but at this moment it's an overkill IMHO always :)

**Comment by hachreak** [comment]
@lnielsen can you remember me how did you resolved it in zenodo? thanks :)
Did you resolve as you proposed with `links_factory`?

**Comment by lnielsen** [comment]
I didn't solve it AFAIR
