### ISSUE TITLE
views: completer suggester endpoint

### ISSUE THREAD

**Issue by lnielsen** [inveniosoftware/invenio-records-rest#54]
Add a new ``../_suggest`` endpoint to Records-REST which will use https://www.elastic.co/guide/en/elasticsearch/reference/current/search-suggesters-completion.html in the backend.

Use case: Auto-completion in deposit forms and search fields.

**Comment by jirikuncar** [comment]
Do we want configuration per field or we want to allow anybody to use `_suggest` endpoint with their own arguments?
