### ISSUE TITLE
utils: move obj_or_import_string to invenio-utils?

### ISSUE THREAD

**Issue by nharraud** [inveniosoftware/invenio-records-rest#88]
As we allow more and more import strings in modules configuration, moving `obj_or_import_string` in `invenio-utils` might be useful.

If time is a concern we can deprecate the one in `invenio-records-rest` and create a new one in `invenio-utils`

**Comment by lnielsen** [comment]
Yes, we should probably move it to a separate package, however the package should have just one objective - e.g. ``importutils`` or something like that - otherwise we'll likely end up with all invenio modules having a dependency on invenio-utils.
