### ISSUE TITLE
views: enable pass_record decorator use resource subclasses

### ISSUE THREAD

**Issue by nharraud** [inveniosoftware/invenio-records-rest#98]
**Use case:**
B2Share needs to customize some of the REST API views. In order to reuse provided resource classes, it would be great if it was possible to subclass them.

**Problem:**
Current [`pass_record` decorator](https://github.com/inveniosoftware/invenio-records-rest/blob/97ac2efcf8b63ab952c0ed9fe999e22b77211ef2/invenio_records_rest/views.py#L279) does not forward some of its arguments, i.e `pid_value`, to the wrapped function. Thus it is not possible to reuse it for subclasses.

**Optimization:**
In order to not try to retrieve the record and pid twice it would be necessary to check in the `pass_record` decorator's parameters if `pid` and `record` are already given (by a subclass calling its super class method).

**Impact on other modules:**
Other modules using `invenio-records-rest` will have to support additional arguments. This impacts at least `invenio-deposit`.

**Comment by jirikuncar** [comment]
@nharraud don't use `@pass_record` but the `request.view_args` together with `url_converter`. We will deprecate `@pass_record` decorator before beta release.

**Comment by nharraud** [comment]
@jirikuncar thanks for the warning. But what is the `url_converter`? I can't find anything named like that in `invenio-records-rest` or in `invenio-rest`.

**Comment by jirikuncar** [comment]
See https://github.com/inveniosoftware/invenio-records-rest/blob/97ac2efcf8b63ab952c0ed9fe999e22b77211ef2/invenio_records_rest/utils.py#L129-L148

**Comment by nharraud** [comment]
Closing issue as `@pass_record` will be deprecated.
